CC=gcc
CFLAGS=-Wall -O -I/usr/local/netcdf/include -I/usr/include/libxml2
LDLIBS=-lm -lxml2 -lz -lpng -L/usr/local/netcdf/lib -lnetcdf 

all: merged_netcdf2png

install: all
	@echo "nothing to install"
